# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-15 07:53
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='作者名')),
                ('work_years', models.IntegerField(default=0, verbose_name='使用年限')),
                ('work_company', models.CharField(max_length=50, verbose_name='公司/学校')),
                ('work_position', models.CharField(max_length=50, verbose_name='职位')),
                ('points', models.CharField(max_length=50, verbose_name='个人特点')),
                ('click_nums', models.IntegerField(default=0, verbose_name='点击数')),
                ('fav_nums', models.IntegerField(default=0, verbose_name='收藏数')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now)),
            ],
            options={
                'verbose_name': '作者',
                'verbose_name_plural': '作者',
            },
        ),
    ]
