# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-17 20:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20171115_1614'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='fans_nums',
            field=models.IntegerField(default=0, verbose_name='粉丝数'),
        ),
    ]
