# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-17 20:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_userprofile_fans_nums'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='age',
            field=models.IntegerField(default=18, verbose_name='年龄'),
        ),
    ]
