# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-15 20:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_auto_20171115_1902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='article/%Y/%m', verbose_name='封面图'),
        ),
    ]
